services:
  vault:
    image: hashicorp/vault:1.13.3
    command: ["vault", "server", "-config", "vault/config/vault-server.hcl"]
    environment:
      VAULT_ADDR: 'http://127.0.0.1:8200'
      VAULT_SKIP_VERIFY: 'true'
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config/vault/config/vault-server.hcl:/vault/config/vault-server.hcl
      - ./data:/vault-data
